export enum ErrorMessage {
  Default = 'DEFAULT',
  PAYMENT_CREATE_DATABASE_EXCEPTION = 'PAYMENT_CREATE_DATABASE_EXCEPTION',
  PAYMENT_UPDATE_DATABASE_EXCEPTION = 'PAYMENT_UPDATE_DATABASE_EXCEPTION',
  PAYMENT_NOT_FOUND_EXCEPTION = 'PAYMENT_NOT_FOUND_EXCEPTION',
  PAYMENT_VALIDATION_EXCEPTION = 'PAYMENT_VALIDATION_EXCEPTION',
  WALLET_SERVICE_EXCEPTION = 'WALLET_SERVICE_EXCEPTION',
}