export enum ErrorMessage {
  Default = 'DEFAULT',
  USER_SAVE_DATABASE_EXCEPTION = 'USER_SAVE_DATABASE_EXCEPTION',
  USER_GET_DATABASE_EXCEPTION = 'USER_GET_DATABASE_EXCEPTION',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
}