export enum ErrorMessage {
  Default = 'DEFAULT',
  WALLET_SAVE_DATABASE_EXCEPTION = 'WALLET_SAVE_DATABASE_EXCEPTION',
  WALLET_GET_DATABASE_EXCEPTION = 'WALLET_GET_DATABASE_EXCEPTION',
  WALLET_NOT_FOUND_EXCEPTION = 'WALLET_NOT_FOUND_EXCEPTION',
}
